PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# code_level_1,label_level_1,code_level_2,label_level_2,code_level_3,label_level_3

SELECT *

WHERE {

  
  ?uri a skos:Concept .
  
  ?uri skos:notation ?code_level_1 .
  ?uri skos:prefLabel ?label_level_1 .
  
  OPTIONAL {
    
    ?uri skos:narrower ?c1 . ?c1 skos:notation ?code_level_2 .
  	?uri skos:narrower ?c1 . ?c1 skos:prefLabel ?label_level_2 .
    
  }
  
  OPTIONAL {
    
    ?uri skos:narrower ?c1 . ?c1 skos:narrower ?c2 . ?c2 skos:notation ?code_level_3 .
  	?uri skos:narrower ?c1 . ?c1 skos:narrower ?c2 . ?c2 skos:prefLabel ?label_level_3 .
    
  }


  
}