PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# code_level_1,label_level_1,code_level_2,label_level_2,code_level_3,label_level_3

SELECT ?code ?label ?uri ?parent 

WHERE {

  ?uri a skos:Concept .
  ?uri skos:notation ?code .
  ?uri skos:prefLabel ?label .
  ?uri skos:broader ?parent .
  
}