
# this is an example query

PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT * 
FROM <http://examples/CLV-AP_IT/>
WHERE { 

	?ontology_uri a owl:Ontology ;

		rdfs:comment ?comment ; 
		rdfs:label ?label ; 

		#owl:imports ?imports ;
		rdfs:isDefinedBy ?definition_uri ;
		dct:license ?license ;

		dc:creator ?creator ;
		dct:issued ?date_issued ;
		dct:modified ?date_modified ;

		owl:versionIRI ?version ;
		owl:versionInfo ?version_info ;
		prov:wasDerivedFrom ?version_from ;

		.
	  
		FILTER(LANG(?comment)='it') 
		FILTER(LANG(?label)='it') 
		#FILTER(LANG(?creator)='en') 
		FILTER(LANG(?version_info)='it') 

}
