# example: vocabulary

DROP GRAPH <test://VocabolariControllati/Licenze/Licenze>
;

LOAD <file:///C:/Users/Al.Serafini/repos/DAF/daf-ontologie-vocabolari-controllati/VocabolariControllati/Licenze/Licenze.ttl>
INTO GRAPH <test://VocabolariControllati/Licenze/Licenze>
;





